/*===================================================================
// Script Number: 308
// Script Name: PMT_CodeModificationRecordNumber.js
// Script Developer: Vance Smith
// Script Agency: Mesa
// Script Description: When "Code Modification" is selected in ASI 
// "Type of Work" then record number is auto assigned, for all other 
// types of work, will be manual generated by staff.

// Script Run Event: ASA

// Script Parents:
//	ASA;Permits!Addenda or Deferrred!NA!NA
//	ASIUA;Permits!Addenda or Deferrred!NA!NA
//            
/*==================================================================*/

/* intellisense references */
/// <reference path="../../INCLUDES_ACCELA_FUNCTIONS-80100.js" />
/// <reference path="../../INCLUDES_ACCELA_GLOBALS-80100.js" />
/// <reference path="../../INCLUDES_CUSTOM.js" />

try
{   
    if (getAppSpecific("Type of Work") != "Code Modification")
    {
        comment("This record's ID can be modified on the summary page.");
    }
    else
    {
        logDebug("Criteria not met.")
    }
}
catch (err)
{
  logDebug("A JavaScript error occurred: " + err.message);
}

/* Test Record: PMT16-00339

*/